java_library(
    name = "gson",
    srcs = glob(["*.java", "**/*.java"]),
    deps = [
        "//gson/src/main/java-templates/com/google/gson/internal:gson_build_config",
    ],
    visibility = ["//visibility:public"],
)
