/* Generated By:JavaCC: Do not edit this line. JsonParserConstants.java */
package com.google.gson;

@SuppressWarnings("all")
interface JsonParserConstants {

  int EOF = 0;
  int E = 5;
  int DIGITS = 6;
  int NULL = 7;
  int BOOLEAN = 8;
  int IDENTIFIER = 9;
  int HEX_CHAR = 10;
  int UNICODE_CHAR = 11;
  int ESCAPE_CHAR = 12;
  int SINGLE_QUOTE_LITERAL = 13;
  int DOUBLE_QUOTE_LITERAL = 14;
  int QUOTE = 15;
  int ENDQUOTE = 17;
  int CHAR = 18;
  int CNTRL_ESC = 19;
  int HEX = 21;
  int HEX_ESC = 22;

  int DEFAULT = 0;
  int STRING_STATE = 1;
  int ESC_STATE = 2;
  int HEX_STATE = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<E>",
    "<DIGITS>",
    "\"null\"",
    "<BOOLEAN>",
    "<IDENTIFIER>",
    "<HEX_CHAR>",
    "<UNICODE_CHAR>",
    "<ESCAPE_CHAR>",
    "<SINGLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
    "\"\\\"\"",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRL_ESC>",
    "\"u\"",
    "<HEX>",
    "<HEX_ESC>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"-\"",
    "\".\"",
  };

}
