/* Generated By:JavaCC: Do not edit this line. JsonParserConstants.java */
package com.google.gson;

@SuppressWarnings("all")
interface JsonParserConstants {

  int EOF = 0;
  int E = 5;
  int DIGITS = 6;
  int ESCAPE_CHAR = 7;
  int SINGLE_QUOTE_LITERAL = 8;
  int QUOTE = 9;
  int ENDQUOTE = 11;
  int CHAR = 12;
  int CNTRL_ESC = 13;
  int HEX = 15;
  int HEX_ESC = 16;

  int DEFAULT = 0;
  int STRING_STATE = 1;
  int ESC_STATE = 2;
  int HEX_STATE = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<E>",
    "<DIGITS>",
    "<ESCAPE_CHAR>",
    "<SINGLE_QUOTE_LITERAL>",
    "\"\\\"\"",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRL_ESC>",
    "\"u\"",
    "<HEX>",
    "<HEX_ESC>",
    "\"{\"",
    "\"}\"",
    "\"null\"",
    "\",\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\"-\"",
    "\".\"",
  };

}
