contact_links:
  - name: Usage question
    url: https://stackoverflow.com/questions/tagged/gson
    about: Ask usage questions on StackOverflow.
  - name: Questions, ideas, tips & tricks, ...
    url: https://github.com/google/gson/discussions
    about: Share information in GitHub Discussions.
