<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by javadoc (build 1.6.0_65) on Thu Nov 20 01:11:55 PST 2014 -->
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<TITLE>
com.google.gson.annotations (Gson 2.3.1 API)
</TITLE>

<META NAME="date" CONTENT="2014-11-20">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../../../../stylesheet.css" TITLE="Style">


</HEAD>

<BODY BGCOLOR="white">
<FONT size="+1" CLASS="FrameTitleFont">
<A HREF="../../../../com/google/gson/annotations/package-summary.html" target="classFrame">com.google.gson.annotations</A></FONT>
<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP><FONT size="+1" CLASS="FrameHeadingFont">
Annotation Types</FONT>&nbsp;
<FONT CLASS="FrameItemFont">
<BR>
<A HREF="Expose.html" title="annotation in com.google.gson.annotations" target="classFrame">Expose</A>
<BR>
<A HREF="JsonAdapter.html" title="annotation in com.google.gson.annotations" target="classFrame">JsonAdapter</A>
<BR>
<A HREF="SerializedName.html" title="annotation in com.google.gson.annotations" target="classFrame">SerializedName</A>
<BR>
<A HREF="Since.html" title="annotation in com.google.gson.annotations" target="classFrame">Since</A>
<BR>
<A HREF="Until.html" title="annotation in com.google.gson.annotations" target="classFrame">Until</A></FONT></TD>
</TR>
</TABLE>


</BODY>
</HTML>
