<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by javadoc (build 1.6.0_65) on Thu Nov 20 01:11:55 PST 2014 -->
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<TITLE>
com.google.gson (Gson 2.3.1 API)
</TITLE>

<META NAME="date" CONTENT="2014-11-20">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../../../stylesheet.css" TITLE="Style">


</HEAD>

<BODY BGCOLOR="white">
<FONT size="+1" CLASS="FrameTitleFont">
<A HREF="../../../com/google/gson/package-summary.html" target="classFrame">com.google.gson</A></FONT>
<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP><FONT size="+1" CLASS="FrameHeadingFont">
Interfaces</FONT>&nbsp;
<FONT CLASS="FrameItemFont">
<BR>
<A HREF="ExclusionStrategy.html" title="interface in com.google.gson" target="classFrame"><I>ExclusionStrategy</I></A>
<BR>
<A HREF="FieldNamingStrategy.html" title="interface in com.google.gson" target="classFrame"><I>FieldNamingStrategy</I></A>
<BR>
<A HREF="InstanceCreator.html" title="interface in com.google.gson" target="classFrame"><I>InstanceCreator</I></A>
<BR>
<A HREF="JsonDeserializationContext.html" title="interface in com.google.gson" target="classFrame"><I>JsonDeserializationContext</I></A>
<BR>
<A HREF="JsonDeserializer.html" title="interface in com.google.gson" target="classFrame"><I>JsonDeserializer</I></A>
<BR>
<A HREF="JsonSerializationContext.html" title="interface in com.google.gson" target="classFrame"><I>JsonSerializationContext</I></A>
<BR>
<A HREF="JsonSerializer.html" title="interface in com.google.gson" target="classFrame"><I>JsonSerializer</I></A>
<BR>
<A HREF="TypeAdapterFactory.html" title="interface in com.google.gson" target="classFrame"><I>TypeAdapterFactory</I></A></FONT></TD>
</TR>
</TABLE>


<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP><FONT size="+1" CLASS="FrameHeadingFont">
Classes</FONT>&nbsp;
<FONT CLASS="FrameItemFont">
<BR>
<A HREF="FieldAttributes.html" title="class in com.google.gson" target="classFrame">FieldAttributes</A>
<BR>
<A HREF="Gson.html" title="class in com.google.gson" target="classFrame">Gson</A>
<BR>
<A HREF="GsonBuilder.html" title="class in com.google.gson" target="classFrame">GsonBuilder</A>
<BR>
<A HREF="JsonArray.html" title="class in com.google.gson" target="classFrame">JsonArray</A>
<BR>
<A HREF="JsonElement.html" title="class in com.google.gson" target="classFrame">JsonElement</A>
<BR>
<A HREF="JsonNull.html" title="class in com.google.gson" target="classFrame">JsonNull</A>
<BR>
<A HREF="JsonObject.html" title="class in com.google.gson" target="classFrame">JsonObject</A>
<BR>
<A HREF="JsonParser.html" title="class in com.google.gson" target="classFrame">JsonParser</A>
<BR>
<A HREF="JsonPrimitive.html" title="class in com.google.gson" target="classFrame">JsonPrimitive</A>
<BR>
<A HREF="JsonStreamParser.html" title="class in com.google.gson" target="classFrame">JsonStreamParser</A>
<BR>
<A HREF="TypeAdapter.html" title="class in com.google.gson" target="classFrame">TypeAdapter</A></FONT></TD>
</TR>
</TABLE>


<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP><FONT size="+1" CLASS="FrameHeadingFont">
Enums</FONT>&nbsp;
<FONT CLASS="FrameItemFont">
<BR>
<A HREF="FieldNamingPolicy.html" title="enum in com.google.gson" target="classFrame">FieldNamingPolicy</A>
<BR>
<A HREF="LongSerializationPolicy.html" title="enum in com.google.gson" target="classFrame">LongSerializationPolicy</A></FONT></TD>
</TR>
</TABLE>


<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP><FONT size="+1" CLASS="FrameHeadingFont">
Exceptions</FONT>&nbsp;
<FONT CLASS="FrameItemFont">
<BR>
<A HREF="JsonIOException.html" title="class in com.google.gson" target="classFrame">JsonIOException</A>
<BR>
<A HREF="JsonParseException.html" title="class in com.google.gson" target="classFrame">JsonParseException</A>
<BR>
<A HREF="JsonSyntaxException.html" title="class in com.google.gson" target="classFrame">JsonSyntaxException</A></FONT></TD>
</TR>
</TABLE>


</BODY>
</HTML>
