// Generated by Quality Playbook v1.5.8 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-06-04 · Project: gson
package com.google.gson.regression;

import static com.google.common.truth.Truth.assertThat;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.Strictness;
import java.math.BigDecimal;
import org.junit.Test;

/**
 * Regression test: toJson and toJsonTree must agree on a finite BigDecimal in STRICT mode.
 */
public class JsonTreeWriterFiniteBigDecimalTest {
  @Test
  public void treeWriterAcceptsFiniteBigDecimalLikeStreamWriter() {
    Gson gson = new GsonBuilder().setStrictness(Strictness.STRICT).create();
    BigDecimal finiteHuge = new BigDecimal("1E400");

    // The bug's defining contract: toJson and toJsonTree must agree on a finite BigDecimal.
    // Pre-fix, toJsonTree threw IllegalArgumentException because JsonTreeWriter.value(Number)
    // routed through doubleValue() which overflows to Infinity for 1E400. Pin both the
    // Number.class and BigDecimal.class type-token dispatch paths so a future adapter-routing
    // refactor cannot green the Number-typed path without also fixing BigDecimal-typed dispatch.
    String stringViaNumber = gson.toJson(finiteHuge, Number.class);
    JsonElement treeViaNumber = gson.toJsonTree(finiteHuge, Number.class);
    assertThat(treeViaNumber.toString()).isEqualTo(stringViaNumber);

    String stringViaBigDecimal = gson.toJson(finiteHuge, BigDecimal.class);
    JsonElement treeViaBigDecimal = gson.toJsonTree(finiteHuge, BigDecimal.class);
    assertThat(treeViaBigDecimal.toString()).isEqualTo(stringViaBigDecimal);
  }
}
